# Variables de entorno de ejemplo (usa prefijo BDI_)
$env:BDI_BACKEND_HOST = "127.0.0.1"
$env:BDI_BACKEND_PORT = "8000"
$env:BDI_MODELS_DIR = "models"
$env:BDI_CORESET_RATE = "0.10"
$env:BDI_SCORE_PERCENTILE = "99"
$env:BDI_AREA_MM2_THR = "1.0"

# Alias opcionales para versiones antiguas (BRAKEDISC_*)
$env:BRAKEDISC_BACKEND_HOST = $env:BDI_BACKEND_HOST
$env:BRAKEDISC_BACKEND_PORT = $env:BDI_BACKEND_PORT
$env:BRAKEDISC_MODELS_DIR = $env:BDI_MODELS_DIR
$env:BRAKEDISC_CORESET_RATE = $env:BDI_CORESET_RATE
$env:BRAKEDISC_SCORE_PERCENTILE = $env:BDI_SCORE_PERCENTILE
$env:BRAKEDISC_AREA_MM2_THR = $env:BDI_AREA_MM2_THR
