# Variables de entorno de ejemplo
$env:BRAKEDISC_BACKEND_HOST = "127.0.0.1"
$env:BRAKEDISC_BACKEND_PORT = "8000"
$env:BRAKEDISC_MODELS_DIR = "models"
$env:BRAKEDISC_CORESET_RATE = "0.10"
$env:BRAKEDISC_SCORE_PERCENTILE = "99"
$env:BRAKEDISC_AREA_MM2_THR = "1.0"
