name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PYTHONPATH: "${{ github.workspace }}:${{ github.workspace }}/backend"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (OpenCV)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
          python -m pip install pytest ruff

      - name: Lint (ruff)
        run: |
          ruff check backend || true

      - name: Run unit tests (unittest)
        working-directory: ${{ github.workspace }}
        run: |
          python -m unittest discover -s backend/tests -t . -p "test_*.py" -v

      - name: Build Docker image
        run: docker build -t brakedisc-backend -f docker/Dockerfile .
